#!/bin/sh
# scripts/install-hooks.sh — install WordBuddy's secrets pre-commit hook.
#
# Usage:
#   sh scripts/install-hooks.sh        # install .git/hooks/pre-commit
#   sh scripts/install-hooks.sh -f     # overwrite an existing hook
#
# What the installed hook does: on every `git commit`, it greps the ADDED
# lines of the staged diff for credential shapes (OpenAI/Anthropic-style
# `sk-…` keys, AWS access-key ids, GitHub tokens, Google API keys, Slack
# tokens, GitLab PATs, literal `Bearer <long-token>` headers, PEM private
# key blocks) and rejects the commit with a message pointing at the
# offending lines. Unstaged work and pre-existing lines are never flagged —
# only what this commit would introduce.
#
# Emergency escape hatch (use sparingly, never for real secrets):
#   WORDBUDDY_SKIP_SECRET_SCAN=1 git commit ...
#
# The hook is NOT installed by running this repo's build; a developer opts
# in by executing this script once per clone. This script does not touch
# anything outside `.git/hooks/pre-commit` and is safe to re-run.
#
# POSIX sh; requires git on PATH.

set -eu

force=0
for arg in "$@"; do
    case "$arg" in
        -f|--force) force=1 ;;
        *) echo "install-hooks.sh: unknown argument '$arg' (usage: sh scripts/install-hooks.sh [-f])" >&2; exit 2 ;;
    esac
done

repo=$(git rev-parse --git-common-dir 2>/dev/null || true)
if [ -z "$repo" ]; then
    echo "install-hooks.sh: not inside a git repository (run from the repo root or a subdirectory)" >&2
    exit 1
fi
hooks_dir=$repo/hooks
mkdir -p "$hooks_dir"
target=$hooks_dir/pre-commit

if [ -f "$target" ] && [ "$force" -ne 1 ]; then
    echo "install-hooks.sh: $target already exists; re-run with -f to overwrite" >&2
    exit 1
fi

cat > "$target" <<'HOOK'
#!/bin/sh
# WordBuddy secrets gate — generated by scripts/install-hooks.sh.
# Scans ADDED staged lines for credential shapes and rejects the commit.
set -u

# Documented one-shot escape hatch (never use for real secrets).
[ "${WORDBUDDY_SKIP_SECRET_SCAN:-0}" = "1" ] && exit 0

added=$(git diff --cached --no-color --no-ext-diff -U0 | grep '^+' | grep -v '^+++')
[ -z "$added" ] && exit 0

pattern='sk-(ant-)?[A-Za-z0-9_-]{20,}|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}|ghp_[A-Za-z0-9]{36}|gho_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{22,}|AIza[0-9A-Za-z_-]{35}|xox[baprs]-[A-Za-z0-9-]{10,}|glpat-[A-Za-z0-9_-]{20,}|[Bb]earer[[:space:]]+[A-Za-z0-9._~+/=-]{24,}|-----BEGIN [A-Z ]*PRIVATE KEY-----'

hits=$(printf '%s\n' "$added" | grep -nE "$pattern")
status=$?

if [ "$status" -eq 0 ]; then
    cat >&2 <<'MSG'
────────────────────────────────────────────────────────────
 COMMIT REJECTED: possible credential in staged content
────────────────────────────────────────────────────────────
Matched added lines are listed above (line numbers are positions
within the added-lines stream). If a match is a real secret,
remove it from the staging area (and rotate it if it was ever
committed anywhere). If it is a false positive (test fixture,
documentation example), amend the line so it no longer matches
(e.g. split the literal) or bypass once with:

  WORDBUDDY_SKIP_SECRET_SCAN=1 git commit ...

────────────────────────────────────────────────────────────
MSG
    printf '%s\n' "$hits" >&2
    exit 1
elif [ "$status" -ne 1 ]; then
    # grep "error" (e.g. pattern compile failure) must not silently pass.
    echo "secrets gate: grep failed with status $status; commit blocked" >&2
    exit 1
fi
exit 0
HOOK

chmod +x "$target"
echo "install-hooks.sh: installed $target"
echo "Test it any time with:  git hook run pre-commit   # or just make a commit"
